import {
  ScaledSheet,
  scale,
  moderateScale,
  verticalScale,
} from 'react-native-size-matters';

export default ScaledSheet.create({
  Estudantes_Title: {
    marginTop: '13@s',
    marginLeft: '15@s',
    color: '#2E8B57',
    fontSize: '20@s',
    fontWeight: 'bold',
  },
  input: {
    backgroundColor: '#fff',
    height: '40@s',
    marginRight: '287@s',
    marginLeft: '17@s',
    marginTop: '10@s',
    borderRadius: '5@s',
    padding: '2@s',
    textAlign: 'center',
    fontSize: '18@s',
    color: '#2E8B57',
  },
  plus: {
    backgroundColor: '#F5F5F5',
    height: '40@s',
    marginRight: '230@s',
    marginLeft: '75@s',
    marginTop: '-40@s',
    borderRadius: '5@s',
    borderTopRightRadius: '0@s',
    borderBottomRightRadius: '0@s',
    padding: '2@s',
    textAlign: 'center',
    fontSize: '18@s',
  },
  minus: {
    backgroundColor: '#F5F5F5',
    height: '40@s',
    marginRight: '17@s',
    marginLeft: '287@s',
    marginTop: '-40@s',
    borderRadius: '5@s',
    borderTopLeftRadius: '0@s',
    borderBottomLeftRadius: '0@s',
    padding: '2@s',
    textAlign: 'center',
    fontSize: '18@s',
  },
  Horas: {
    backgroundColor: '#FFF',
    height: '40@s',
    marginRight: '57@s',
    marginLeft: '113@s',
    marginTop: '-40@s',
    borderRadius: '5@s',
    padding: '2@s',
    justifyContent: 'center',
  },
  HoraStyle: {
    textAlign: 'center',
    fontSize: '14@s',
    color: '#2E8B57' + '60',
  },
  OpcionalStyle: {
    fontSize: '12@s',
    color: '#000000' + '60',
  },
  inputLetters: {
    backgroundColor: '#fff',
    height: '100@s',
    marginRight: '20@s',
    marginLeft: '17@s',
    marginTop: '10@s',
    borderRadius: '5@s',
    padding: '3@s',
    paddingBottom: '80@s',
    fontSize: '14@s',
    color: '#2E8B57',
    shadowColor: '#000',
  },
  Check: {
    position: 'relative',

    width: '55@s',
    height: '55@s',
    borderRadius: '30@s',
    top: '-45@s', //margimTop: '-90@s'
    bottom: '10@s',
    marginLeft: '280@s',
    backgroundColor: '#008000',

    shadowColor: '#000',
    shadowOffset: {
      width: '0@s',
      height: '2@s',
    },
    shadowOpacity: '0.25@s',
    shadowRadius: '4@s',
    elevation: '5@s',
  },
  centeredView: {
    flex: '1@s',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    borderRadius: '20@s',
    padding: '50@s',
    paddingBottom: '15@s',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: '0@s',
      height: '2@s',
    },
    shadowOpacity: '0.25@s',
    shadowRadius: '4@s',
    elevation: '5@s',
  },
  button: {
    borderRadius: '5@s',
    padding: '13@s',
    paddingLeft: '50@s',
    paddingRight: '50@s',
    elevation: '2@s',
  },
  buttonOpen: {
    backgroundColor: '#fff',
  },
  button1: {
    borderRadius: '5@s',
    padding: '13@s',
    paddingBottom: '10@s',
    marginLeft: '15@s',
    marginRight: '15@s',
    elevation: '2@s',
    marginTop: '10@s',
  },
  buttonClose: {
    backgroundColor: '#006400',
  },
  textStyle: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  button2: {
    borderRadius: '5@s',
    padding: '13@s',
    marginLeft: '15@s',
    marginRight: '15@s',
    elevation: '2@s',
    marginTop: '20@s',
  },
  textStyle2: {
    color: '#2E8B57' + '80',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: '14@s',
  },
  modalText: {
    marginBottom: '10@s',
    textAlign: 'center',
  },
  text: {
    fontSize: '15@s',
    marginLeft: '27@s',
    fontWeight: '500',
  },
  textSemana: {
    color: '#000000' + '70',
    fontSize: '15@s',
    marginLeft: '27@s',
    fontWeight: '250',
  },
  textMes: {
    color: '#000000' + '70',
    fontSize: '15@s',
    marginLeft: '27@s',
    fontWeight: '250',
  },
});
